/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Marks = IDL.Record({
  'marks' : IDL.Int,
  'subjectId' : IDL.Text,
  'examType' : IDL.Text,
});
export const Subject = IDL.Record({
  'semester' : IDL.Nat,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'subjectId' : IDL.Text,
  'department' : IDL.Text,
});
export const Time = IDL.Int;
export const FeesDue = IDL.Record({
  'dueDate' : Time,
  'yearSemester' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Exam = IDL.Record({
  'date' : Time,
  'subjectId' : IDL.Text,
  'examId' : IDL.Text,
  'examType' : IDL.Text,
});
export const Attendance = IDL.Record({
  'subjectId' : IDL.Text,
  'percentage' : IDL.Float64,
});
export const Degree = IDL.Variant({
  'mba' : IDL.Null,
  'bTech' : IDL.Null,
  'mTech' : IDL.Null,
});
export const Student = IDL.Record({
  'studentId' : IDL.Text,
  'degree' : Degree,
  'department' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const AcademicRecord = IDL.Record({
  'marks' : IDL.Vec(Marks),
  'subjects' : IDL.Vec(Subject),
  'feesDue' : IDL.Vec(FeesDue),
  'exams' : IDL.Vec(Exam),
  'attendance' : IDL.Vec(Attendance),
  'student' : Student,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Course = IDL.Record({
  'branch' : IDL.Text,
  'durationYears' : IDL.Nat16,
  'degree' : Degree,
});
export const FeeStructure = IDL.Record({
  'yearSemesterBreakdown' : IDL.Vec(
    IDL.Record({ 'yearOrSemester' : IDL.Text, 'amount' : IDL.Float64 })
  ),
  'course' : Course,
});
export const UserProfile = IDL.Record({
  'studentId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const FacultyMember = IDL.Record({
  'name' : IDL.Text,
  'subjectsTaught' : IDL.Vec(IDL.Text),
  'department' : IDL.Text,
  'qualification' : IDL.Text,
});
export const FAQEntry = IDL.Record({
  'keywords' : IDL.Vec(IDL.Text),
  'response' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateAcademicRecord' : IDL.Func([IDL.Text, AcademicRecord], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllAcademicRecords' : IDL.Func([], [IDL.Vec(AcademicRecord)], ['query']),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllFeeStructures' : IDL.Func([], [IDL.Vec(FeeStructure)], ['query']),
  'getAttendanceByStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatbotResponse' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getDepartmentInfo' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'courses' : IDL.Vec(Course),
          'subjects' : IDL.Vec(Subject),
          'faculty' : IDL.Vec(FacultyMember),
        }),
      ],
      ['query'],
    ),
  'getExamTimetableByDepartment' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Exam)],
      ['query'],
    ),
  'getFAQEntries' : IDL.Func([], [IDL.Vec(FAQEntry)], ['query']),
  'getFacultyByDepartment' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FacultyMember)],
      ['query'],
    ),
  'getFacultyDirectory' : IDL.Func([], [IDL.Vec(FacultyMember)], ['query']),
  'getFeeStructureByCourse' : IDL.Func([Course], [FeeStructure], ['query']),
  'getFeesDueByStudent' : IDL.Func([IDL.Text], [IDL.Vec(FeesDue)], ['query']),
  'getMarksByStudent' : IDL.Func([IDL.Text], [IDL.Vec(Marks)], ['query']),
  'getOwnRecord' : IDL.Func([], [AcademicRecord], ['query']),
  'getStudentRecord' : IDL.Func([IDL.Text], [AcademicRecord], ['query']),
  'getSubjectsByDepartment' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Subject)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Marks = IDL.Record({
    'marks' : IDL.Int,
    'subjectId' : IDL.Text,
    'examType' : IDL.Text,
  });
  const Subject = IDL.Record({
    'semester' : IDL.Nat,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'subjectId' : IDL.Text,
    'department' : IDL.Text,
  });
  const Time = IDL.Int;
  const FeesDue = IDL.Record({
    'dueDate' : Time,
    'yearSemester' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Exam = IDL.Record({
    'date' : Time,
    'subjectId' : IDL.Text,
    'examId' : IDL.Text,
    'examType' : IDL.Text,
  });
  const Attendance = IDL.Record({
    'subjectId' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  const Degree = IDL.Variant({
    'mba' : IDL.Null,
    'bTech' : IDL.Null,
    'mTech' : IDL.Null,
  });
  const Student = IDL.Record({
    'studentId' : IDL.Text,
    'degree' : Degree,
    'department' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const AcademicRecord = IDL.Record({
    'marks' : IDL.Vec(Marks),
    'subjects' : IDL.Vec(Subject),
    'feesDue' : IDL.Vec(FeesDue),
    'exams' : IDL.Vec(Exam),
    'attendance' : IDL.Vec(Attendance),
    'student' : Student,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Course = IDL.Record({
    'branch' : IDL.Text,
    'durationYears' : IDL.Nat16,
    'degree' : Degree,
  });
  const FeeStructure = IDL.Record({
    'yearSemesterBreakdown' : IDL.Vec(
      IDL.Record({ 'yearOrSemester' : IDL.Text, 'amount' : IDL.Float64 })
    ),
    'course' : Course,
  });
  const UserProfile = IDL.Record({
    'studentId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const FacultyMember = IDL.Record({
    'name' : IDL.Text,
    'subjectsTaught' : IDL.Vec(IDL.Text),
    'department' : IDL.Text,
    'qualification' : IDL.Text,
  });
  const FAQEntry = IDL.Record({
    'keywords' : IDL.Vec(IDL.Text),
    'response' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateAcademicRecord' : IDL.Func([IDL.Text, AcademicRecord], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllAcademicRecords' : IDL.Func(
        [],
        [IDL.Vec(AcademicRecord)],
        ['query'],
      ),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllFeeStructures' : IDL.Func([], [IDL.Vec(FeeStructure)], ['query']),
    'getAttendanceByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatbotResponse' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getDepartmentInfo' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'courses' : IDL.Vec(Course),
            'subjects' : IDL.Vec(Subject),
            'faculty' : IDL.Vec(FacultyMember),
          }),
        ],
        ['query'],
      ),
    'getExamTimetableByDepartment' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Exam)],
        ['query'],
      ),
    'getFAQEntries' : IDL.Func([], [IDL.Vec(FAQEntry)], ['query']),
    'getFacultyByDepartment' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FacultyMember)],
        ['query'],
      ),
    'getFacultyDirectory' : IDL.Func([], [IDL.Vec(FacultyMember)], ['query']),
    'getFeeStructureByCourse' : IDL.Func([Course], [FeeStructure], ['query']),
    'getFeesDueByStudent' : IDL.Func([IDL.Text], [IDL.Vec(FeesDue)], ['query']),
    'getMarksByStudent' : IDL.Func([IDL.Text], [IDL.Vec(Marks)], ['query']),
    'getOwnRecord' : IDL.Func([], [AcademicRecord], ['query']),
    'getStudentRecord' : IDL.Func([IDL.Text], [AcademicRecord], ['query']),
    'getSubjectsByDepartment' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Subject)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };