/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AcademicRecord {
  'marks' : Array<Marks>,
  'subjects' : Array<Subject>,
  'feesDue' : Array<FeesDue>,
  'exams' : Array<Exam>,
  'attendance' : Array<Attendance>,
  'student' : Student,
}
export interface Attendance { 'subjectId' : string, 'percentage' : number }
export interface Course {
  'branch' : string,
  'durationYears' : number,
  'degree' : Degree,
}
export type Degree = { 'mba' : null } |
  { 'bTech' : null } |
  { 'mTech' : null };
export interface Exam {
  'date' : Time,
  'subjectId' : string,
  'examId' : string,
  'examType' : string,
}
export interface FAQEntry { 'keywords' : Array<string>, 'response' : string }
export interface FacultyMember {
  'name' : string,
  'subjectsTaught' : Array<string>,
  'department' : string,
  'qualification' : string,
}
export interface FeeStructure {
  'yearSemesterBreakdown' : Array<
    { 'yearOrSemester' : string, 'amount' : number }
  >,
  'course' : Course,
}
export interface FeesDue {
  'dueDate' : Time,
  'yearSemester' : string,
  'amount' : number,
}
export interface Marks {
  'marks' : bigint,
  'subjectId' : string,
  'examType' : string,
}
export interface Student {
  'studentId' : string,
  'degree' : Degree,
  'department' : string,
  'lastName' : string,
  'firstName' : string,
}
export interface Subject {
  'semester' : bigint,
  'code' : string,
  'name' : string,
  'year' : bigint,
  'subjectId' : string,
  'department' : string,
}
export type Time = bigint;
export interface UserProfile {
  'studentId' : [] | [string],
  'name' : string,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateAcademicRecord' : ActorMethod<
    [string, AcademicRecord],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllAcademicRecords' : ActorMethod<[], Array<AcademicRecord>>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllFeeStructures' : ActorMethod<[], Array<FeeStructure>>,
  'getAttendanceByStudent' : ActorMethod<[string], Array<Attendance>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatbotResponse' : ActorMethod<[string], string>,
  'getDepartmentInfo' : ActorMethod<
    [string],
    {
      'courses' : Array<Course>,
      'subjects' : Array<Subject>,
      'faculty' : Array<FacultyMember>,
    }
  >,
  'getExamTimetableByDepartment' : ActorMethod<[string], Array<Exam>>,
  'getFAQEntries' : ActorMethod<[], Array<FAQEntry>>,
  'getFacultyByDepartment' : ActorMethod<[string], Array<FacultyMember>>,
  'getFacultyDirectory' : ActorMethod<[], Array<FacultyMember>>,
  'getFeeStructureByCourse' : ActorMethod<[Course], FeeStructure>,
  'getFeesDueByStudent' : ActorMethod<[string], Array<FeesDue>>,
  'getMarksByStudent' : ActorMethod<[string], Array<Marks>>,
  'getOwnRecord' : ActorMethod<[], AcademicRecord>,
  'getStudentRecord' : ActorMethod<[string], AcademicRecord>,
  'getSubjectsByDepartment' : ActorMethod<[string], Array<Subject>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];