/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FAQEntry {
    keywords: Array<string>;
    response: string;
}
export interface UserProfile {
    studentId?: string;
    name: string;
    role: string;
}
export type Time = bigint;
export interface Attendance {
    subjectId: string;
    percentage: number;
}
export interface Marks {
    marks: bigint;
    subjectId: string;
    examType: string;
}
export interface AcademicRecord {
    marks: Array<Marks>;
    subjects: Array<Subject>;
    feesDue: Array<FeesDue>;
    exams: Array<Exam>;
    attendance: Array<Attendance>;
    student: Student;
}
export interface FeeStructure {
    yearSemesterBreakdown: Array<{
        yearOrSemester: string;
        amount: number;
    }>;
    course: Course;
}
export interface Course {
    branch: string;
    durationYears: number;
    degree: Degree;
}
export interface Exam {
    date: Time;
    subjectId: string;
    examId: string;
    examType: string;
}
export interface FacultyMember {
    name: string;
    subjectsTaught: Array<string>;
    department: string;
    qualification: string;
}
export interface FeesDue {
    dueDate: Time;
    yearSemester: string;
    amount: number;
}
export interface Subject {
    semester: bigint;
    code: string;
    name: string;
    year: bigint;
    subjectId: string;
    department: string;
}
export interface Student {
    studentId: string;
    degree: Degree;
    department: string;
    lastName: string;
    firstName: string;
}
export enum Degree {
    mba = "mba",
    bTech = "bTech",
    mTech = "mTech"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addOrUpdateAcademicRecord(studentId: string, record: AcademicRecord): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllAcademicRecords(): Promise<Array<AcademicRecord>>;
    getAllCourses(): Promise<Array<Course>>;
    getAllFeeStructures(): Promise<Array<FeeStructure>>;
    getAttendanceByStudent(studentId: string): Promise<Array<Attendance>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatbotResponse(message: string): Promise<string>;
    getDepartmentInfo(department: string): Promise<{
        courses: Array<Course>;
        subjects: Array<Subject>;
        faculty: Array<FacultyMember>;
    }>;
    getExamTimetableByDepartment(department: string): Promise<Array<Exam>>;
    getFAQEntries(): Promise<Array<FAQEntry>>;
    getFacultyByDepartment(department: string): Promise<Array<FacultyMember>>;
    getFacultyDirectory(): Promise<Array<FacultyMember>>;
    getFeeStructureByCourse(course: Course): Promise<FeeStructure>;
    getFeesDueByStudent(studentId: string): Promise<Array<FeesDue>>;
    getMarksByStudent(studentId: string): Promise<Array<Marks>>;
    getOwnRecord(): Promise<AcademicRecord>;
    getStudentRecord(studentId: string): Promise<AcademicRecord>;
    getSubjectsByDepartment(department: string): Promise<Array<Subject>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { AcademicRecord as _AcademicRecord, Attendance as _Attendance, Course as _Course, Degree as _Degree, Exam as _Exam, FacultyMember as _FacultyMember, FeeStructure as _FeeStructure, FeesDue as _FeesDue, Marks as _Marks, Student as _Student, Subject as _Subject, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addOrUpdateAcademicRecord(arg0: string, arg1: AcademicRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateAcademicRecord(arg0, to_candid_AcademicRecord_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateAcademicRecord(arg0, to_candid_AcademicRecord_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllAcademicRecords(): Promise<Array<AcademicRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAcademicRecords();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAcademicRecords();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCourses();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCourses();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFeeStructures(): Promise<Array<FeeStructure>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeeStructures();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeeStructures();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceByStudent(arg0: string): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByStudent(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatbotResponse(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatbotResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatbotResponse(arg0);
            return result;
        }
    }
    async getDepartmentInfo(arg0: string): Promise<{
        courses: Array<Course>;
        subjects: Array<Subject>;
        faculty: Array<FacultyMember>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepartmentInfo(arg0);
                return from_candid_record_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepartmentInfo(arg0);
            return from_candid_record_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExamTimetableByDepartment(arg0: string): Promise<Array<Exam>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExamTimetableByDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExamTimetableByDepartment(arg0);
            return result;
        }
    }
    async getFAQEntries(): Promise<Array<FAQEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFAQEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFAQEntries();
            return result;
        }
    }
    async getFacultyByDepartment(arg0: string): Promise<Array<FacultyMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFacultyByDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFacultyByDepartment(arg0);
            return result;
        }
    }
    async getFacultyDirectory(): Promise<Array<FacultyMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFacultyDirectory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFacultyDirectory();
            return result;
        }
    }
    async getFeeStructureByCourse(arg0: Course): Promise<FeeStructure> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeStructureByCourse(to_candid_Course_n29(this._uploadFile, this._downloadFile, arg0));
                return from_candid_FeeStructure_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeStructureByCourse(to_candid_Course_n29(this._uploadFile, this._downloadFile, arg0));
            return from_candid_FeeStructure_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeesDueByStudent(arg0: string): Promise<Array<FeesDue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeesDueByStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeesDueByStudent(arg0);
            return result;
        }
    }
    async getMarksByStudent(arg0: string): Promise<Array<Marks>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarksByStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarksByStudent(arg0);
            return result;
        }
    }
    async getOwnRecord(): Promise<AcademicRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnRecord();
                return from_candid_AcademicRecord_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnRecord();
            return from_candid_AcademicRecord_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentRecord(arg0: string): Promise<AcademicRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentRecord(arg0);
                return from_candid_AcademicRecord_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentRecord(arg0);
            return from_candid_AcademicRecord_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubjectsByDepartment(arg0: string): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjectsByDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjectsByDepartment(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AcademicRecord_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AcademicRecord): AcademicRecord {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Course_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Course): Course {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Degree_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Degree): Degree {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_FeeStructure_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeStructure): FeeStructure {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marks: Array<_Marks>;
    subjects: Array<_Subject>;
    feesDue: Array<_FeesDue>;
    exams: Array<_Exam>;
    attendance: Array<_Attendance>;
    student: _Student;
}): {
    marks: Array<Marks>;
    subjects: Array<Subject>;
    feesDue: Array<FeesDue>;
    exams: Array<Exam>;
    attendance: Array<Attendance>;
    student: Student;
} {
    return {
        marks: value.marks,
        subjects: value.subjects,
        feesDue: value.feesDue,
        exams: value.exams,
        attendance: value.attendance,
        student: from_candid_Student_n12(_uploadFile, _downloadFile, value.student)
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: string;
    degree: _Degree;
    department: string;
    lastName: string;
    firstName: string;
}): {
    studentId: string;
    degree: Degree;
    department: string;
    lastName: string;
    firstName: string;
} {
    return {
        studentId: value.studentId,
        degree: from_candid_Degree_n14(_uploadFile, _downloadFile, value.degree),
        department: value.department,
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    branch: string;
    durationYears: number;
    degree: _Degree;
}): {
    branch: string;
    durationYears: number;
    degree: Degree;
} {
    return {
        branch: value.branch,
        durationYears: value.durationYears,
        degree: from_candid_Degree_n14(_uploadFile, _downloadFile, value.degree)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    yearSemesterBreakdown: Array<{
        yearOrSemester: string;
        amount: number;
    }>;
    course: _Course;
}): {
    yearSemesterBreakdown: Array<{
        yearOrSemester: string;
        amount: number;
    }>;
    course: Course;
} {
    return {
        yearSemesterBreakdown: value.yearSemesterBreakdown,
        course: from_candid_Course_n17(_uploadFile, _downloadFile, value.course)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: [] | [string];
    name: string;
    role: string;
}): {
    studentId?: string;
    name: string;
    role: string;
} {
    return {
        studentId: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.studentId)),
        name: value.name,
        role: value.role
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    courses: Array<_Course>;
    subjects: Array<_Subject>;
    faculty: Array<_FacultyMember>;
}): {
    courses: Array<Course>;
    subjects: Array<Subject>;
    faculty: Array<FacultyMember>;
} {
    return {
        courses: from_candid_vec_n16(_uploadFile, _downloadFile, value.courses),
        subjects: value.subjects,
        faculty: value.faculty
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mba: null;
} | {
    bTech: null;
} | {
    mTech: null;
}): Degree {
    return "mba" in value ? Degree.mba : "bTech" in value ? Degree.bTech : "mTech" in value ? Degree.mTech : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Course>): Array<Course> {
    return value.map((x)=>from_candid_Course_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeeStructure>): Array<FeeStructure> {
    return value.map((x)=>from_candid_FeeStructure_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AcademicRecord>): Array<AcademicRecord> {
    return value.map((x)=>from_candid_AcademicRecord_n10(_uploadFile, _downloadFile, x));
}
function to_candid_AcademicRecord_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AcademicRecord): _AcademicRecord {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Course_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Course): _Course {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_Degree_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Degree): _Degree {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Student_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Student): _Student {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marks: Array<Marks>;
    subjects: Array<Subject>;
    feesDue: Array<FeesDue>;
    exams: Array<Exam>;
    attendance: Array<Attendance>;
    student: Student;
}): {
    marks: Array<_Marks>;
    subjects: Array<_Subject>;
    feesDue: Array<_FeesDue>;
    exams: Array<_Exam>;
    attendance: Array<_Attendance>;
    student: _Student;
} {
    return {
        marks: value.marks,
        subjects: value.subjects,
        feesDue: value.feesDue,
        exams: value.exams,
        attendance: value.attendance,
        student: to_candid_Student_n3(_uploadFile, _downloadFile, value.student)
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    branch: string;
    durationYears: number;
    degree: Degree;
}): {
    branch: string;
    durationYears: number;
    degree: _Degree;
} {
    return {
        branch: value.branch,
        durationYears: value.durationYears,
        degree: to_candid_Degree_n5(_uploadFile, _downloadFile, value.degree)
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId?: string;
    name: string;
    role: string;
}): {
    studentId: [] | [string];
    name: string;
    role: string;
} {
    return {
        studentId: value.studentId ? candid_some(value.studentId) : candid_none(),
        name: value.name,
        role: value.role
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: string;
    degree: Degree;
    department: string;
    lastName: string;
    firstName: string;
}): {
    studentId: string;
    degree: _Degree;
    department: string;
    lastName: string;
    firstName: string;
} {
    return {
        studentId: value.studentId,
        degree: to_candid_Degree_n5(_uploadFile, _downloadFile, value.degree),
        department: value.department,
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Degree): {
    mba: null;
} | {
    bTech: null;
} | {
    mTech: null;
} {
    return value == Degree.mba ? {
        mba: null
    } : value == Degree.bTech ? {
        bTech: null
    } : value == Degree.mTech ? {
        mTech: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
